### ISSUE TITLE
Map lIghting on Alien Mode.

### ISSUE THREAD

**Issue by molamaster999** [PerfectScrash/ZP-Special-Final#7]
Hello, PerfectScrash. I hope you have a wonderful day. I really enjoy your mod so far. I just want to report some bug. During alien round, there is no darkness around like in Assassin round. Map lighting is set to very bright. When I check the code on zpsp_special_class_alien.sma, zp_set_lighting is set to "a"  value, but the map lighting like is set to "z" value, really bright. No matter I change the value, map still is set to very bright. I think there's something wrong with zp_set_lighting native and I can't figure it out yet.

Here's the image of map lighting when Alien round occurs.
![20230813165646_1](https://github.com/PerfectScrash/ZP-Special-Final/assets/43886620/8646cee7-fc9f-40e0-8dc9-f9393c44f78e)

**Comment by PerfectScrash** [comment]
Thanks for report, issue fixed
